# Generated by Django 4.2.5 on 2023-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
